# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(help_text='Input the Attention To name here if the person is purchasing on behalf of a company or business', max_length=32, verbose_name='Customer Name')),
                ('contact_email', models.CharField(max_length=200, verbose_name='E-mail')),
                ('contact_num', models.CharField(max_length=40, verbose_name='Phone Number')),
                ('business_name', models.CharField(blank=True, help_text='Leave blank if no company details are provided', max_length=60, unique=True, verbose_name='Business Registered Name')),
                ('business_reg_no', models.CharField(blank=True, max_length=10, verbose_name='Business Registration Number')),
                ('billing_address_1', models.CharField(max_length=60, verbose_name='Billing Address Line 1')),
                ('billing_address_2', models.CharField(max_length=60, verbose_name='Billing Address Line 2')),
                ('billing_postal', models.CharField(max_length=60, verbose_name='Billing Postal Code')),
                ('industry', models.CharField(choices=[('NON', 'Home, Office'), ('FNB', 'Food and Beverage, Hotel, Restaurant'), ('EVT', 'Event, Pasar Malam'), ('BAR', 'Bars, Pubs, Clubs'), ('IND', 'Industrial, Concrete, Manufacturing'), ('MAR', 'Minimart, Supermarket'), ('WTM', 'Wetmarket'), ('OTR', 'Other')], default='NON', max_length=3)),
            ],
        ),
    ]
