# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='billing_address_2',
            field=models.CharField(blank=True, max_length=60, verbose_name='Billing Address Line 2'),
        ),
    ]
