# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20170715_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
    ]
