# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 06:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0003_customer_is_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='industry',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_created_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_created_by_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='lead_created_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='lead_created_by_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='lead_owned_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='lead_owned_by_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_address_1',
            field=models.CharField(blank=True, max_length=60, verbose_name='Billing Address Line 1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_postal',
            field=models.CharField(blank=True, max_length=60, verbose_name='Billing Postal Code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='business_name',
            field=models.CharField(blank=True, max_length=60, unique=True, verbose_name='Business Registered Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='business_reg_no',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Business Registration Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=32, verbose_name='Customer Name'),
        ),
    ]
