# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 06:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0004_auto_20170717_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_owned_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_owned_by_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
