# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20170718_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=32, verbose_name='Contact Name'),
        ),
    ]
