# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 07:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20170724_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_creator', to=settings.AUTH_USER_MODEL, verbose_name='Customer Created By'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_owner', to=settings.AUTH_USER_MODEL, verbose_name='Customer Owned By'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lead_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_creator', to=settings.AUTH_USER_MODEL, verbose_name='Lead Created By'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lead_owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_owner', to=settings.AUTH_USER_MODEL, verbose_name='Lead Owned By'),
        ),
    ]
