# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 14:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20170715_0120'),
        ('customers', '0006_auto_20170717_2232'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address1', models.CharField(max_length=200, verbose_name='Shipping Address Line 1')),
                ('shipping_address2', models.CharField(blank=True, max_length=200, verbose_name='Shipping Address Line 2')),
                ('shipping_postal', models.CharField(max_length=60, verbose_name='Shipping Postal')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('quote_total', models.BooleanField(default=False)),
                ('quote_gst', models.BooleanField(default=False)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Customer Name')),
            ],
        ),
        migrations.CreateModel(
            name='Quote_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.PositiveIntegerField(verbose_name='Price')),
                ('product_description', models.TextField(max_length=300, verbose_name='Product Description')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Product Name')),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.Quote', verbose_name='Quote ID')),
            ],
        ),
    ]
