# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_auto_20170718_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_products',
            name='product_description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='quote_products',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price'),
        ),
    ]
