# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_auto_20170718_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_products',
            name='product_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Product Description'),
        ),
    ]
