# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_auto_20170718_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
