# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_quote_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='template_type',
            field=models.CharField(choices=[('T1', 'Template 1: GST Excluded, Quantity Required'), ('T2', 'Template 2: GST Included, Quantity Required'), ('T3', 'Template 3: GST Excluded, Quantity Not Required'), ('T4', 'Template 4: GST Included, Quantity Not Required')], default='T3', max_length=2),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Contact Name'),
        ),
    ]
