# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_auto_20170724_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_products',
            name='product_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Product Quantity'),
        ),
    ]
