# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_quote_products_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_products',
            name='product_line_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Line Total'),
        ),
    ]
