# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_quote_products_product_line_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quote_gst',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quote_total',
        ),
        migrations.AlterField(
            model_name='quote',
            name='template_type',
            field=models.CharField(choices=[('T1', 'Template 1: GST Excluded, Quantity Required, Total Shown'), ('T2', 'Template 2: GST Included, Quantity Required, Total Shown'), ('T3', 'Template 3: GST Excluded, Quantity Not Required'), ('T4', 'Template 4: GST Included, Quantity Not Required')], default='T3', max_length=2),
        ),
    ]
