# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_auto_20170726_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Price'),
        ),
    ]
