# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_quote_quote_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total'),
        ),
    ]
