# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0011_auto_20170726_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total'),
        ),
    ]
